import { Inter, Playfair_Display } from 'next/font/google';
import Header from './components/Header';
import Footer from './components/Footer';
import './globals.css';

// Configure the fonts
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Create a CSS variable
  display: 'swap',
});

const playfair_display = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair-display', // Create a CSS variable
  display: 'swap',
});

export const metadata = {
  title: 'My Awesome Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    // Apply the font variables to the html tag
    <html lang="en" className={`${inter.variable} ${playfair_display.variable}`}>
      <body className="bg-primary text-text-dark"> {/* Set default background and text color */}
        <Header />
        <main className="container mx-auto p-4">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}